version: "3"
services:
  brain_mri_postop:
    image: brain_mri_postop 
    build: ./
    environment:
      - "TZ=America/New_York"
      - storage=/app/data/incoming/postop
      - log=/app/logs/postop
      - aetitle=BRAIN_MRI_POSTOP
      - aeport=11112
    volumes:
      - /app/brats_receive_mri:/app
      - /data/btseg:/app/data
    ports:
      - '11113:11112'
    restart: always

